### ISSUE TITLE
Stop trying to read proxool

### ISSUE THREAD

**Issue by guusdk** [igniterealtime/openfire-jmxweb-plugin#4]
Proxool was replaced with Apache Commons DBCP in Openfire 4.3.0 (OF-1419).

Using the JMXWeb plugin in a version that's later can cause this error to be logged:

```
2020.10.27 16:33:22 ERROR [pool-29-thread-1]: org.jivesoftware.openfire.container.PluginManager - An exception occurred while loading plugin 'jmxweb':
java.lang.NoClassDefFoundError: org/logicalcobwebs/proxool/ProxoolException
        at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_265]
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[?:1.8.0_265]
        at java.lang.Class.privateGetPublicMethods(Class.java:2902) ~[?:1.8.0_265]
        at java.lang.Class.getMethods(Class.java:1615) ~[?:1.8.0_265]
        at com.sun.jmx.mbeanserver.MBeanIntrospector.getMethods(MBeanIntrospector.java:181) ~[?:1.8.0_265]
        at com.sun.jmx.mbeanserver.MBeanAnalyzer.initMaps(MBeanAnalyzer.java:128) ~[?:1.8.0_265]
        at com.sun.jmx.mbeanserver.MBeanAnalyzer.<init>(MBeanAnalyzer.java:118) ~[?:1.8.0_265]
        at com.sun.jmx.mbeanserver.MBeanAnalyzer.analyzer(MBeanAnalyzer.java:102) ~[?:1.8.0_265]
        at com.sun.jmx.mbeanserver.StandardMBeanIntrospector.getAnalyzer(StandardMBeanIntrospector.java:67) ~[?:1.8.0_265]
        at com.sun.jmx.mbeanserver.MBeanIntrospector.getPerInterface(MBeanIntrospector.java:192) ~[?:1.8.0_265]
        at com.sun.jmx.mbeanserver.MBeanSupport.<init>(MBeanSupport.java:138) ~[?:1.8.0_265]
        at com.sun.jmx.mbeanserver.StandardMBeanSupport.<init>(StandardMBeanSupport.java:60) ~[?:1.8.0_265]
        at com.sun.jmx.mbeanserver.Introspector.makeDynamicMBean(Introspector.java:192) ~[?:1.8.0_265]
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject(DefaultMBeanServerInterceptor.java:898) ~[?:1.8.0_265]
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:324) ~[?:1.8.0_265]
        at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522) ~[?:1.8.0_265]
        at com.javamonitor.JmxHelper.register(JmxHelper.java:85) ~[jmxweb-lib.jar!/:?]
        at com.ifsoft.jmxweb.plugin.JmxWebPlugin.initializePlugin(JmxWebPlugin.java:108) ~[jmxweb-lib.jar!/:?]
        at org.jivesoftware.openfire.container.PluginManager.loadPlugin(PluginManager.java:683) [xmppserver-4.7.0-SNAPSHOT.jar:4.7.0-SNAPSHOT]
        at org.jivesoftware.openfire.container.PluginMonitor$MonitorTask$4.call(PluginMonitor.java:375) [xmppserver-4.7.0-SNAPSHOT.jar:4.7.0-SNAPSHOT]
        at org.jivesoftware.openfire.container.PluginMonitor$MonitorTask$4.call(PluginMonitor.java:363) [xmppserver-4.7.0-SNAPSHOT.jar:4.7.0-SNAPSHOT]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_265]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_265]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_265]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
Caused by: java.lang.ClassNotFoundException: org.logicalcobwebs.proxool.ProxoolException
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_265]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_265]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_265]
        ... 25 more
```

**Comment by guusdk** [comment]
This was actually fixed in release 0.0.8, but that version never got a proper release.
